### ISSUE TITLE
CSS Variable prefix/type not handled properly

### ISSUE THREAD

**Issue by hikarinai** [tenoxui/css#31]
*note: Indonesian language alert!*

# Isu pada fitur CSS Variable Class Name

## Tentang Isu
Isu terjadi apabila kita menambahkan `CSS variable` atau `Custom Value` kedalam `value`.

## Konfigurasi
Seluruh prefix kelas yang digunakan dan propeti css nya :
```js
use({
  property: [
    {
      c: "--my-color",
      bg: "background",
      text: "color"
    }
  ]
});
```

## CSS
Mendifinisikan variable `--blue` yang akan dipakai di dalam nama kelas di html :
```css
:root {
  --blue: red; /* warna merah */
}
```

### Kode Yang Berkerja

```html
<h1 class="text-$blue">Ini Bekerja</h1>
<h1 class="[--blue]-cyan text-$blue">Ini Bekerja</h1>
<h1 class="c-blue text-$blue">Ini Bekerja</h1>
```

### Kode yang Tidak Bekerja

```html
<h1 class="c-[--blue] text-$my-color">Ini Tidak Bekerja</h1>
<h1 class="[--blue]-orange c-$blue text-$blue">Ini Tidak Bekerja</h1>
<h1 class="[--color]-$blue text-$color">Ini Tidak Bekerja</h1>
```

## Penjelasan

Semua kode yang tidak bekerja adalah dari fitur `css variable` **yang mengambil value dari `css variable yang lain.**

### Kode yang bekerja

```html
<h1 class="text-$blue">Ini Bekerja</h1>
```

Kode tersebut bekerja karena value diambil langsung dari variable `--blue` dari css.

### Kode yang tidak bekerja

```html
<h1 class="[--color]-$blue text-$color">Ini Tidak Bekerja</h1>
```

Walaupun variable `--color` mengambil value dari `--blue`, ini tidak bekerja.

## Kesimpulan

Mungkin `handler` untuk css variable tidak bekerja dengan baik? Dan ini menyebabkan seluruh `types` yang berkaitan dengan css variable tidak ditangani dengan baik, dan ini menyebabkan value dengan `$value` atau `[value]` tidak bekerja.

_by Nia ❤️_

**Comment by nousantx** [comment]
Thanks @hikarinai. Isu ini karena value untuk css variable tidak memiliki handler :

```ts
// Old code
if (typeof property === "string" && property.startsWith("--")) {
  this.element.style.setProperty(property, value + unit);
}
```

Dan di versi yang akan datang, akan menjadi seperti ini kurang lebih :

```ts
let nextValue = value + unit;

if (value.startsWith("$")) {
  nextValue = `var(--${value.slice(1)})`;
} else if (value.startsWith("[") && value.endsWith("]")) {
  nextValue = value.slice(1, -1).replace(/\\_/g, " ");
}

if (type.startsWith("[--") && type.endsWith("]")) {
  this.ELEMENT.style.setProperty(type.slice(1, -1), nextValue);
}

if (typeof property === "string" && property.startsWith("--")) {
  this.ELEMENT.style.setProperty(property, nextValue);
}
```
